"""debug scheme 2.0

Revision ID: efff42ca404f
Revises: 
Create Date: 2025-05-17 14:32:05.756883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efff42ca404f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID Users'),
    sa.Column('tg_id', sa.BigInteger(), nullable=False, comment='ID Telegram'),
    sa.Column('first_name', sa.String(length=64), nullable=True, comment='Name user'),
    sa.Column('last_name', sa.String(length=64), nullable=True, comment='Surname user'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='login by user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('habits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID Habit'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID Users'),
    sa.Column('name_habit', sa.String(length=128), nullable=False, comment='Name Habit'),
    sa.Column('date_start', sa.DateTime(), nullable=False, comment='Date start'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habitlogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID Checkin'),
    sa.Column('habit_id', sa.Integer(), nullable=False, comment='ID Habit'),
    sa.Column('date_log', sa.DateTime(), nullable=False, comment='Date checkin'),
    sa.Column('done', sa.Boolean(), nullable=False, comment='Done checkin'),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('habitlog')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitlog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='ID Checkin'),
    sa.Column('habit_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID Habit'),
    sa.Column('date_log', sa.DATE(), autoincrement=False, nullable=False, comment='Date checkin'),
    sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Done checkin'),
    sa.PrimaryKeyConstraint('id', name='habitlog_pkey')
    )
    op.drop_table('habitlogs')
    op.drop_table('habits')
    op.drop_table('users')
    # ### end Alembic commands ###
